name: Gerar Mancha SHP Refinada

on:
  workflow_dispatch: # Botão para rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev

      - name: Instalar bibliotecas Python
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install rasterio geopandas pandas requests fiona shapely pysheds scipy scikit-image

      - name: Executar Gerador de Mancha
        run: |
          # Cria a pasta antes para o upload não falhar
          mkdir -p output
          python gerador_mancha.py

      - name: Upload do Shapefile Gerado
        uses: actions/upload-artifact@v4
        with:
          name: Mancha_Inundacao_Resultados
          path: output/
          if-no-files-found: error
