name: Dam Break Simulation Job

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python Libraries
        run: |
          pip install numpy pandas rasterio geopandas shapely gdown

      - name: Run Dam Break Script
        run: python gerador_mancha.py

      - name: Save and Push Results
        run: |
          git config --global user.name 'DamBreakBot'
          git config --global user.email 'bot@noreply.github.com'
          git add manchas_output/*.geojson
          git diff --quiet && git diff --staged --quiet || (git commit -m "Novas manchas de inundação geradas" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
